config/routes.rb
Rails.application.routes.draw do

  resources :questions do
    resources :answers, only: [:index, :show, :create] do
      post 'vote-best'
    end
  end

  get '/auth/:provider/callback', to: 'sessions#create'

  delete '/logout', to: 'sessions#destroy'

  get '*unmatched_route', to: 'application#raise_not_found'

  root 'questions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  #these associations may change as application progresses
  belongs_to :question
  belongs_to :user

  validates :body, presence: true, length: { minimum: 50 }
  validates :question_id, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def self.to_markdown(string)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, autolink: true, tables: true, fenced_code_blocks: true)
    if string.nil?
      return ""
    else
      markdown.render(string).html_safe
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  #these associations may change as application progresses
  has_many :answers, dependent: :destroy
  belongs_to :user

  validates :title, presence: true, length: { minimum: 20 }
  validates :description, presence: true, length: { minimum: 50 }
  validates :user_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions
  has_many :answers

  validates :provider, presence: true
  validates :uid, presence: true, uniqueness: true
  validates :nickname, presence: true, uniqueness: true
  validates :name, presence: true
  validates :email, allow_blank: true, format: { with: /\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}\b/i }
  validates :avatar_url, presence: true, format: { with: /([a-zA-Z]+):\/\/(-\.)?(([^\s\/?\.#\-]+|([^\s\/?\.#\-]-[^\s\/?\.#\-]))\.?)+(\/[^\s]*)?/i }
  validates :token, presence: true, uniqueness: true


  def self.find_or_create_by_auth(auth)
    user = User.find_or_create_by(provider: auth['provider'], uid: auth['uid'])

    user.nickname = auth['info']['nickname']
    user.name = auth['info']['name']
    user.email = auth['info']['email']
    user.avatar_url = auth['info']['image']
    user.token = auth['credentials']['token']
    user.save
    user
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def index
    @question = Question.find(params[:question_id])
    @answers = @question.answers
  end

  def show
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
  end

  def create
    if current_user
      @best_answer = nil
      @question = Question.find(answer_params[:question_id])
      @submitted_answer = Answer.new(answer_params)
      if @submitted_answer.save
        redirect_to question_path(@question.id)
      else
        if !@question.best_answer.nil?
          @best_answer = @question.answers.where('id = ?', @question.best_answer).first.body
          @answers = @question.answers.where('id != ?', @question.best_answer).order(created_at: :desc)
        else
          @answers = @question.answers.order(created_at: :desc)
        end
        @errors = @submitted_answer.errors.full_messages
        render "questions/show"
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def vote_best
    @question = Question.find(vote_params[:question_id])
    if current_user && @question.user_id === current_user.id
      @question.best_answer = vote_params[:answer_id].to_i
      @question.save
      redirect_to question_path(@question.id)
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def vote_params
    params.permit(:question_id, :answer_id)
  end

  def answer_params
    params.require(:answer).permit(:body, :question_id, :user_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  rescue_from ActiveRecord::RecordNotFound, with: :not_found
  rescue_from ActionController::RoutingError, with: :not_found

  helper_method :current_user

	def current_user
	   @current_user ||= User.find(session[:user_id]) if session[:user_id]
	end

	def authorize!
	   redirect_to root_path unless current_user
	end

  def raise_not_found
    raise ActionController::RoutingError.new("No route matches #{params[:unmatched_route]}")
  end

  def not_found
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/404", layout: false, status: :not_found }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end

  def error
    respond_to do |format|
      format.html { render file: "#{Rails.root}/public/500", layout: false, status: :error }
      format.xml { head :not_found }
      format.any { head :not_found }
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @recent_questions = Question.order(created_at: :desc)
  end

  def show
  @errors = nil
  @best_answer = nil
  @question = Question.find(params[:id])
  if !@question.best_answer.nil?
    @best_answer = @question.answers.where('id = ?', @question.best_answer).first.body
    @answers = @question.answers.where('id != ?', @question.best_answer).order(created_at: :desc)
  else
    @answers = @question.answers.order(created_at: :desc)
  end
  @submitted_answer = @question.answers.new
end

  def new
    if current_user
      @errors = nil
      @question = Question.new
    else
      flash[:notice] = "You must be signed in"
      redirect_to root_path
    end
  end

  def edit
    @question = Question.find(params[:id])
    if current_user && @question.user_id === current_user.id
      @errors = nil
    else
      redirect_to root_path
    end
  end

  def update
    @question = Question.find(params[:id])
    if current_user && @question.user_id === current_user.id
      @question.title = question_params[:title]
      @question.description = question_params[:description]
      if @question.save
        redirect_to questions_path
      else
        @errors = @question.errors.full_messages
        render :edit
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def create
    if current_user
      @question = Question.new(question_params)
      @question.user_id = current_user.id
      if @question.save
        redirect_to questions_path
      else
        @errors = @question.errors.full_messages
        render :new
      end
    end
  end

  def destroy
    if current_user
      @question = Question.find(params[:id])
      if @question.user_id === current_user.id
        @question.destroy
        redirect_to questions_path
      end
    else
      redirect_back(fallback_location: root_path)
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_or_create_by_auth(request.env['omniauth.auth'])
    if @user
      session[:user_id] = @user.id
      flash[:notice] = "Welcome, #{@user.name}"
      redirect_to questions_path
    else
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out"
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/index.html.erb
<h1><%= @question.title %></h1>
<h2>Answers</h2>
<ul>
  <% @answers.each do |answer| %>
    <li><%= answer.body %></li>
  <% end %>
</ul>

app/views/answers/show.html.erb
<h1><%= @answer.body %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RescueMission</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="top-bar">
      <div class="container">
        <ul class="top-bar-section">
          <li><%= link_to 'Home', questions_path, class: 'button' %></li>
          <% if current_user %>
            <li>Signed in as <%= current_user.name %></li>
            <li><%= link_to "Sign Out", logout_path, method: "DELETE", class: "button" %></li>
          <% else %>
            <li><%= link_to "Sign In", "/auth/github", class: "button" %></li>
          <% end %>
        </ul>
      </div>
    </div>

    <% if flash.any? %>
      <div class="flash">
        <div class="container">
          <%= flash[:notice] %>
          <a href='?' id='flash-close'>&#10005</a>
        </div>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/questions/edit.html.erb
<h1>Edit Question</h1>
<h4><%= @question.title %></h4>
<% if !@errors.nil? %>
  <div class="errors">
    <p><%= @errors.join(", ") %></p>
  </div>
<% end %>
<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, size: @question.title.size %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "60x10" %>
  </div>

  <div class="actions">
    <%= f.submit "Update Question" %>
  </div>
<% end %>
<%= link_to "Delete", question_path(@question.id), class: "button", method: :delete %>

app/views/questions/index.html.erb
<h1>Recent Questions</h1>
<%= link_to 'Submit Question', new_question_path, class: 'button' %>
<% @recent_questions.each do |question| %>
  <p class="recent_questions"><%= link_to question.title, question_path(question.id) %></p>
<% end %>

app/views/questions/new.html.erb
<h1>Submit a question</h1>
<% if !@errors.nil? %>
  <div class="errors">
    <p><%= @errors.join(", ") %></p>
  </div>
<% end %>
<%= form_for(@question) do |f| %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, size: "60x10" %>
  </div>

  <div class="actions">
    <%= f.submit "Submit Question" %>
  </div>
<% end %>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>
<h4>Question</h4>
<div class="response-block">
  <%= ApplicationRecord.to_markdown(@question.description) %>
</div>
<% if current_user %>
  <% if @question.user_id === current_user.id %>
    <%= link_to "Edit", edit_question_path(@question), class: "button" %>
  <% end %>
  <h2>Submit an answer</h2>
  <% if @errors %>
    <div class="errors">
      <p><%= @errors.join(", ") %></p>
    </div>
  <% end %>
  <%= form_for [@question, @submitted_answer] do |f| %>
    <div class="field">
      <%= f.text_area :body, id: "body", size: "60x10" %>
      <%= f.hidden_field :question_id %>
      <%= f.hidden_field :user_id, value: current_user.id %>
    </div>

    <div class="actions">
      <%= f.submit "Submit Answer" %>
    </div>
  <% end %>
<% end %>


<h4>Answers</h4>
<% if @question.best_answer %>
  <div class="response-block">
    <h4>Voted Best Answer</h4>
    <%= ApplicationRecord.to_markdown(@best_answer) %>
  </div>
<% end %>
<% if @answers.empty? && @question.best_answer.nil? %>
  <h4>There are no answers yet</h4>
<% else %>
  <% @answers.each do |answer| %>

    <div class="response-block">
      <% if @question.best_answer.nil? && current_user && @question.user_id === current_user.id %>
        <%= link_to "Vote Best", question_answer_vote_best_path(@question.id, answer.id), id: "vote_best_#{answer.id}", method: "POST", class: "button" %>
      <% end %>
      <%= ApplicationRecord.to_markdown(answer.body) %>
    </div>
  <% end %>
<% end %>